name: Convert Files to PDF

on:
  push:
    branches: [ main ]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice
        pip install Pillow

    - name: Convert images to PDF
      run: |
        python <<EOF
        from PIL import Image
        import os

        image_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.tiff']
        image_files = [f for f in os.listdir('.') if os.path.splitext(f)[1].lower() in image_extensions]

        if image_files:
            images = []
            for file in image_files:
                img = Image.open(file)
                img = img.convert('RGB')
                images.append(img)
            images[0].save('images_converted.pdf', save_all=True, append_images=images[1:])
        EOF

    - name: Convert Word documents to PDF
      run: |
        word_extensions=".doc .docx"
        for ext in $word_extensions; do
          for file in *$ext; do
            [ -e "$file" ] || continue
            libreoffice --headless --convert-to pdf "$file"
          done
        done

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Convert files to PDF'
        add: '*.pdf'
